export default Object.freeze({
  ACCOUNT: "Account",
  AGENDA: "Agenda",
  BLUEPRINT: "Blueprint",
  CANDIDATE: "Candidate",
  CANDIDATES: "Candidates",
  CANDIDATE_DASHBOARD: "CandidateDashboard",
  CANDIDATE_DETAILS: "CandidateDetails",
  GOVERNORSHIP: "Governorship",
  GOVERNORSHIP_CANDIDATES: "GovernorshipCandidates",
  LOGIN: "Login",
  LOGIN_ASPIRANT: "LoginAspirant",
  PRESIDENTIAL_CANDIDATES: "PresidentialCandidates",
  PREVIOUS_ACHIEVEMENTS: "PreviousAchievements",
  PROFILE: "Profile",
  PUBLIC_PROFILE: "PublicProfile",
  QUOTES: "Quotes",
  REGISTER: "Register",
  REGISTER_ASPIRANT: "RegisterAspirant",
  SOCIAL_RESPONSIBILITY: "SocialResponsibility",
  UPDATE_ASPIRANT: "UpdateAspirant",
  VIEW_ASPIRANTS: "ViewAspirants",
});
